export type TiposRotas = {
    primeiraTela: undefined, // padrão para não dar erro.
    Login: undefined,
    CriarUsuario: undefined,
    TelaPrincipal: undefined,
    PerfilUsuario: {usuarioAtual: string, status_usuario: string},
    AdicionarAmigos: {usuarioAtual: string, nome: string},
    Ranking: {usuarioAtual: string},
    Dieta: undefined,
    CriarDieta: undefined,
    DietaCriada: {objetivo: any, preco: any, peso: any, altura: any, restricoes: any},
    GeradorReceita: {usuarioAtual: string},
    ReceitasApp: undefined,
    ReceitasCarnivoraApp: undefined,
    ReceitasCarnivoraAppBASE: undefined,
    ReceitasVegetarianaAppBASE: undefined,
    ReceitasVegetarianaApp: undefined,
    ReceitasVeganaAppBASE: undefined,
    ReceitasVeganaApp: undefined,
};
