export type TiposRotas = {
    primeiraTela: undefined, // padrão para não dar erro.
    Login: undefined,
    CriarUsuario: undefined,
    TelaPrincipal: undefined,
    PerfilUsuario: {usuarioAtual: string, status_usuario: string},
    AdicionarAmigos: {usuarioAtual: string, nome: string, AdicionarAmigos_ou_Ver_Seguidores: boolean},
    Ranking: {usuarioAtual: string},
    Dieta: undefined,
    CriarDieta: undefined,
    DietaCriada: {objetivo: any, preco: any, peso: any, altura: any, restricoes: any},
    GeradorReceita: {usuarioAtual: string},
    Receitas: undefined,
    ReceitasCarnivoraApp: undefined,
    ReceitasCarnivoraAppBASE: undefined,
    ReceitasVegetarianaAppBASE: undefined,
    ReceitasVegetarianaApp: undefined,
    ReceitasVeganaAppBASE: undefined,
    ReceitasVeganaApp: undefined,
    ReceitasCarnivoraUsuarios: undefined,
    ReceitasCarnivoraUsuariosBASE: undefined,
    ReceitasVegetarianaUsuariosBASE: undefined,
    ReceitasVegetarianaUsuarios: undefined,
    ReceitasVeganaUsuariosBASE: undefined,
    ReceitasVeganaUsuarios: undefined,
    Receita: {recipe: any},
    ReceitasFavoritas: {nome: string, usuarioAtual: string},
    CriarReceita: undefined,
    ReceitasCriadas: {nome: string, usuarioAtual: string},
};
